backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image, default: "/img/books-4305459_640.jpg"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          # - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          # - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          # - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: subtitle, widget: string}
          - {label: Image, name: heroImage, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/joanna/index.md"
        label: "Joanna"
        name: "joanna"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "joanna-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: subtitle, widget: string}
          - {label: Image, name: heroImage, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/life-samtaler/index.md"
        label: "Life Samtaler"
        name: "life-samtaler"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "life-samtaler"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: subtitle, widget: string}
          - {label: Image, name: heroImage, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/life-events/index.md"
        label: "Life Events"
        name: "life-events"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "life-events"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: subtitle, widget: string}
          - {label: Image, name: heroImage, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/life-shops/index.md"
        label: "Life Shops"
        name: "life-shops"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "life-shops"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: subtitle, widget: string}
          - {label: Image, name: heroImage, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}